## Testing Alpaca API

In [1]:
import os

from alpaca.data import (
    OptionHistoricalDataClient,
)
from alpaca.data.requests import OptionChainRequest
from dotenv import load_dotenv

load_dotenv()

api_key = os.getenv("ALPACA_API_KEY")
api_secret = os.getenv("ALPACA_API_SECRET")

option_client = OptionHistoricalDataClient(api_key, api_secret)

In [4]:
from utils.alpaca_utils import flatten_option_data

req = OptionChainRequest(underlying_symbol="SPY",limit=1000,type="call")
chain_data = option_client.get_option_chain(request_params=req)

records = flatten_option_data(chain_data)
df = pl.DataFrame(records)

In [5]:
df.with_columns(date=pl.col("trade_timestamp").dt.date())

shape: (5_195, 24)
┌───────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ symbol    ┆ implied_v ┆ greek_del ┆ greek_gam ┆ … ┆ trade_id ┆ trade_con ┆ trade_tap ┆ date      │
│ ---       ┆ olatility ┆ ta        ┆ ma        ┆   ┆ ---      ┆ ditions   ┆ e         ┆ ---       │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ null     ┆ ---       ┆ ---       ┆ date      │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆          ┆ str       ┆ null      ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ SPY260107 ┆ 0.101     ┆ 0.0157    ┆ 0.0063    ┆ … ┆ null     ┆ I         ┆ null      ┆ 2026-01-0 │
│ C00697000 ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ 2         │
│ SPY260108 ┆ 0.1173    ┆ 0.5709    ┆ 0.0468    ┆ … ┆ null     ┆ I         ┆ null      ┆ 2026-01-0 │
│ C00682000 ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ 2         │
│ SPY260108 ┆ 0.2177    ┆ 0.9532    ┆ 0.0063    ┆ … ┆ null     ┆ null      ┆ null      ┆ null      │
│ C00658000 ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ SPY260112 ┆ null      ┆ null      ┆ null      ┆ … ┆ null     ┆ null      ┆ null      ┆ null      │
│ C00570000 ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ SPY260107 ┆ 0.1488    ┆ 0.8731    ┆ 0.0226    ┆ … ┆ null     ┆ I         ┆ null      ┆ 2026-01-0 │
│ C00673000 ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ 2         │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …        ┆ …         ┆ …         ┆ …         │
│ SPY280616 ┆ 0.1425    ┆ 0.2959    ┆ 0.0023    ┆ … ┆ null     ┆ I         ┆ null      ┆ 2025-12-3 │
│ C00855000 ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ 1         │
│ SPY280616 ┆ 0.199     ┆ 0.9736    ┆ 0.0003    ┆ … ┆ null     ┆ f         ┆ null      ┆ 2025-12-2 │
│ C00425000 ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ 3         │
│ SPY280616 ┆ null      ┆ null      ┆ null      ┆ … ┆ null     ┆ null      ┆ null      ┆ null      │
│ C00355000 ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ SPY280616 ┆ 0.1844    ┆ 0.6691    ┆ 0.0018    ┆ … ┆ null     ┆ I         ┆ null      ┆ 2026-01-0 │
│ C00680000 ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ 2         │
│ SPY280616 ┆ null      ┆ null      ┆ null      ┆ … ┆ null     ┆ null      ┆ null      ┆ null      │
│ C00230000 ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

In [88]:
df.filter(pl.col("symbol").str.starts_with("SPY260109C000680"))

shape: (0, 23)
┌────────┬────────────┬────────────┬────────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ symbol ┆ implied_vo ┆ greek_delt ┆ greek_gamm ┆ … ┆ trade_siz ┆ trade_id ┆ trade_con ┆ trade_tap │
│ ---    ┆ latility   ┆ a          ┆ a          ┆   ┆ e         ┆ ---      ┆ ditions   ┆ e         │
│ str    ┆ ---        ┆ ---        ┆ ---        ┆   ┆ ---       ┆ null     ┆ ---       ┆ ---       │
│        ┆ f64        ┆ f64        ┆ f64        ┆   ┆ f64       ┆          ┆ str       ┆ null      │
╞════════╪════════════╪════════════╪════════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
└────────┴────────────┴────────────┴────────────┴───┴───────────┴──────────┴───────────┴───────────┘

In [79]:
df.with_columns(strike=pl.col("symbol").str.slice(11, 5)).select("symbol", "strike").sort("strike",descending=True)

shape: (655, 2)
┌─────────────────────┬────────┐
│ symbol              ┆ strike │
│ ---                 ┆ ---    │
│ str                 ┆ str    │
╞═════════════════════╪════════╡
│ ASTS260220C00150000 ┆ 00150  │
│ ASTS270319C00150000 ┆ 00150  │
│ ASTS270115C00150000 ┆ 00150  │
│ ASTS271217C00150000 ┆ 00150  │
│ ASTS260618C00150000 ┆ 00150  │
│ …                   ┆ …      │
│ ASTS260116C00002000 ┆ 00002  │
│ ASTS260116C00002500 ┆ 00002  │
│ ASTS260116C00001000 ┆ 00001  │
│ ASTS260116C00001500 ┆ 00001  │
│ ASTS260116C00000500 ┆ 00000  │
└─────────────────────┴────────┘

## Testing post-no-preference's options data

https://www.dolthub.com/repositories/post-no-preference/options/data/master

In [9]:
import polars as pl

df = pl.read_parquet("../backtest/data/options_master.parquet")

In [113]:
df.filter(pl.col("act_symbol") == "GME",
pl.col("date")>"2023-12-19").group_by("act_symbol", "expiration","strike").agg(
    pl.count(),
    pl.col("date").min().alias("min_date"),
    pl.col("date").max().alias("max_date"),
).sort("count",descending=True)

C:\Users\Akshay Sadanandan\AppData\Local\Temp\ipykernel_40724\811418958.py:3: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  pl.count(),

shape: (3_383, 6)
┌────────────┬────────────┬────────┬───────┬────────────┬────────────┐
│ act_symbol ┆ expiration ┆ strike ┆ count ┆ min_date   ┆ max_date   │
│ ---        ┆ ---        ┆ ---    ┆ ---   ┆ ---        ┆ ---        │
│ str        ┆ str        ┆ f64    ┆ u32   ┆ str        ┆ str        │
╞════════════╪════════════╪════════╪═══════╪════════════╪════════════╡
│ GME        ┆ 2026-01-16 ┆ 20.0   ┆ 56    ┆ 2025-11-11 ┆ 2026-01-02 │
│ GME        ┆ 2025-04-17 ┆ 25.0   ┆ 56    ┆ 2025-02-10 ┆ 2025-04-07 │
│ GME        ┆ 2025-04-17 ┆ 23.0   ┆ 56    ┆ 2025-02-10 ┆ 2025-04-07 │
│ GME        ┆ 2026-01-16 ┆ 21.0   ┆ 56    ┆ 2025-11-11 ┆ 2026-01-02 │
│ GME        ┆ 2026-01-16 ┆ 19.0   ┆ 56    ┆ 2025-11-11 ┆ 2026-01-02 │
│ …          ┆ …          ┆ …      ┆ …     ┆ …          ┆ …          │
│ GME        ┆ 2024-06-14 ┆ 38.0   ┆ 2     ┆ 2024-05-15 ┆ 2024-05-15 │
│ GME        ┆ 2025-04-25 ┆ 29.5   ┆ 2     ┆ 2025-04-14 ┆ 2025-04-14 │
│ GME        ┆ 2024-08-23 ┆ 17.0   ┆ 2     ┆ 2024-08-12 ┆ 2024-08-12 │
│ GME        ┆ 2024-06-07 ┆ 25.5   ┆ 2     ┆ 2024-05-22 ┆ 2024-05-22 │
│ GME        ┆ 2024-11-22 ┆ 29.5   ┆ 2     ┆ 2024-11-11 ┆ 2024-11-11 │
└────────────┴────────────┴────────┴───────┴────────────┴────────────┘

In [10]:
df.filter(pl.col("act_symbol") == "GME")['date'].min()

'2019-11-09'

In [40]:
df.filter(pl.col("act_symbol") == "AAPL").with_columns(
    opname=pl.col("act_symbol")
    + "_"
    + pl.col("expiration")
    + "_"
    + pl.col("strike").cast(pl.Int64).cast(pl.Utf8)
).group_by("opname").agg(pl.col("date").unique()).sort(pl.col("opname"))

shape: (14_762, 2)
┌─────────────────────┬─────────────────────────────────┐
│ opname              ┆ date                            │
│ ---                 ┆ ---                             │
│ str                 ┆ list[str]                       │
╞═════════════════════╪═════════════════════════════════╡
│ AAPL_2019-02-22_145 ┆ ["2019-02-09"]                  │
│ AAPL_2019-02-22_152 ┆ ["2019-02-09"]                  │
│ AAPL_2019-02-22_157 ┆ ["2019-02-09"]                  │
│ AAPL_2019-02-22_162 ┆ ["2019-02-09"]                  │
│ AAPL_2019-02-22_167 ┆ ["2019-02-09"]                  │
│ …                   ┆ …                               │
│ AAPL_2026-02-20_340 ┆ ["2025-12-17", "2025-12-18", …… │
│ AAPL_2026-02-20_345 ┆ ["2025-12-16"]                  │
│ AAPL_2026-02-20_350 ┆ ["2025-12-17", "2025-12-22", "… │
│ AAPL_2026-02-20_355 ┆ ["2025-12-18", "2025-12-19", …… │
│ AAPL_2026-02-20_360 ┆ ["2025-12-16"]                  │
└─────────────────────┴─────────────────────────────────┘

In [8]:
df.filter(pl.col("act_symbol") == "GME")

shape: (108_974, 13)
┌────────────┬────────────┬────────────┬────────┬───┬────────┬─────────┬────────┬─────────┐
│ date       ┆ act_symbol ┆ expiration ┆ strike ┆ … ┆ gamma  ┆ theta   ┆ vega   ┆ rho     │
│ ---        ┆ ---        ┆ ---        ┆ ---    ┆   ┆ ---    ┆ ---     ┆ ---    ┆ ---     │
│ str        ┆ str        ┆ str        ┆ f64    ┆   ┆ f64    ┆ f64     ┆ f64    ┆ f64     │
╞════════════╪════════════╪════════════╪════════╪═══╪════════╪═════════╪════════╪═════════╡
│ 2019-11-09 ┆ GME        ┆ 2019-11-22 ┆ 5.0    ┆ … ┆ 0.1505 ┆ -0.0039 ┆ 0.0015 ┆ 0.0018  │
│ 2019-11-09 ┆ GME        ┆ 2019-11-22 ┆ 5.0    ┆ … ┆ 0.1673 ┆ -0.0051 ┆ 0.0019 ┆ -0.0002 │
│ 2019-11-09 ┆ GME        ┆ 2019-11-22 ┆ 5.5    ┆ … ┆ 0.344  ┆ -0.0086 ┆ 0.0034 ┆ 0.0016  │
│ 2019-11-09 ┆ GME        ┆ 2019-11-22 ┆ 5.5    ┆ … ┆ 0.3255 ┆ -0.01   ┆ 0.0036 ┆ -0.0005 │
│ 2019-11-09 ┆ GME        ┆ 2019-11-22 ┆ 6.0    ┆ … ┆ 0.4752 ┆ -0.0117 ┆ 0.0047 ┆ 0.0012  │
│ …          ┆ …          ┆ …          ┆ …      ┆ … ┆ …      ┆ …       ┆ …      ┆ …       │
│ 2026-01-02 ┆ GME        ┆ 2026-02-20 ┆ 25.0   ┆ … ┆ 0.0728 ┆ -0.0081 ┆ 0.0186 ┆ -0.0164 │
│ 2026-01-02 ┆ GME        ┆ 2026-02-20 ┆ 26.0   ┆ … ┆ 0.0575 ┆ -0.0102 ┆ 0.0178 ┆ 0.0038  │
│ 2026-01-02 ┆ GME        ┆ 2026-02-20 ┆ 26.0   ┆ … ┆ 0.0598 ┆ -0.0125 ┆ 0.0212 ┆ -0.0185 │
│ 2026-01-02 ┆ GME        ┆ 2026-02-20 ┆ 27.0   ┆ … ┆ 0.0475 ┆ -0.0087 ┆ 0.0151 ┆ 0.003   │
│ 2026-01-02 ┆ GME        ┆ 2026-02-20 ┆ 27.0   ┆ … ┆ 0.0524 ┆ -0.0127 ┆ 0.0194 ┆ -0.019  │
└────────────┴────────────┴────────────┴────────┴───┴────────┴─────────┴────────┴─────────┘